/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visuales;

import Base_de_Datos.Gestion;
import clases.Estudiante;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import utiles.Secuencias_cadenas;
import utiles.Tupla;

/**
 *
 * @author joanmanuel
 */
public class Crear_brigada extends javax.swing.JFrame {

    private Gestion G = new Gestion();
    private Vector<Estudiante> estudiantes;

    public Crear_brigada() {
        initComponents();

        estudiantes = new Vector<>();
    }

    public Crear_brigada(String Carr) {
        initComponents();

        estudiantes = new Vector<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregar_estudiante = new javax.swing.JDialog();
        nombre = new javax.swing.JLabel();
        nombreT = new javax.swing.JTextField();
        CI = new javax.swing.JLabel();
        CIT = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        MenuEstudiantes = new javax.swing.JPopupMenu();
        EditarEstudiante = new javax.swing.JMenuItem();
        EliminarEstudiante = new javax.swing.JMenuItem();
        Seleccionar_carrera = new javax.swing.JButton();
        Carrera_seleccionada = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEst = new javax.swing.JTable();
        AnnosCombo = new javax.swing.JComboBox<>();
        Annos = new javax.swing.JLabel();
        Finalizar = new javax.swing.JButton();
        Agregar_estudiante = new javax.swing.JButton();

        nombre.setText("Nombre y Apellidos:");

        nombreT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreTKeyReleased(evt);
            }
        });

        CI.setText("Carnet de Identidad:");

        CIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CITKeyReleased(evt);
            }
        });

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout agregar_estudianteLayout = new javax.swing.GroupLayout(agregar_estudiante.getContentPane());
        agregar_estudiante.getContentPane().setLayout(agregar_estudianteLayout);
        agregar_estudianteLayout.setHorizontalGroup(
            agregar_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregar_estudianteLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(agregar_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(agregar_estudianteLayout.createSequentialGroup()
                        .addComponent(nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreT, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(agregar_estudianteLayout.createSequentialGroup()
                        .addComponent(CI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(agregar_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Aceptar)
                            .addComponent(CIT))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        agregar_estudianteLayout.setVerticalGroup(
            agregar_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregar_estudianteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(agregar_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(nombreT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(agregar_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CI)
                    .addComponent(CIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(Aceptar)
                .addContainerGap())
        );

        EditarEstudiante.setText("jMenuItem1");
        EditarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarEstudianteActionPerformed(evt);
            }
        });
        MenuEstudiantes.add(EditarEstudiante);

        EliminarEstudiante.setText("jMenuItem2");
        EliminarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEstudianteActionPerformed(evt);
            }
        });
        MenuEstudiantes.add(EliminarEstudiante);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Seleccionar_carrera.setText("Seleccionar Carrera");
        Seleccionar_carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seleccionar_carreraActionPerformed(evt);
            }
        });

        TablaEst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaEst);

        Annos.setText("Anno");

        Finalizar.setText("Finalizar");

        Agregar_estudiante.setText("Agregar Estudiante");
        Agregar_estudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_estudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Carrera_seleccionada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Seleccionar_carrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Annos)
                                .addGap(18, 18, 18)
                                .addComponent(AnnosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Agregar_estudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Finalizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Seleccionar_carrera)
                        .addGap(18, 18, 18)
                        .addComponent(Carrera_seleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AnnosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Annos))
                        .addGap(61, 61, 61)
                        .addComponent(Agregar_estudiante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Finalizar)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Seleccionar_carreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seleccionar_carreraActionPerformed
        Gestor_carreras GC = new Gestor_carreras(false);
        GC.setVisible(true);
        // this.setEnabled(false);
    }//GEN-LAST:event_Seleccionar_carreraActionPerformed

    private void Agregar_estudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_estudianteActionPerformed

        agregar_estudiante.setVisible(true);


    }//GEN-LAST:event_Agregar_estudianteActionPerformed

    private void nombreTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTKeyReleased
        if (Secuencias_cadenas.sonNumeros(evt.getKeyChar())) {

            Character caracterEtrada = evt.getKeyChar();
            String reeplazo = nombreT.getText().replaceAll(caracterEtrada.toString(), "");
            nombreT.setText(reeplazo);
        }
    }//GEN-LAST:event_nombreTKeyReleased

    private void CITKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CITKeyReleased

        Secuencias_cadenas.borrarLetras(evt.getKeyChar(), CIT);

    }//GEN-LAST:event_CITKeyReleased

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed

        //acordarse de la verificacion del CI conchetumadre
        String[] nombre = nombreT.getText().split(" ");

        if (nombre.length < 3) {
            JOptionPane.showMessageDialog(null, "Este nombre no es viable. Se necesitan al menos dos apellidos.");
            return;
        }

        Estudiante E = new Estudiante(nombreT.getText(), CIT.getText());

        boolean flag = G.agregar_estudiante(E);
        if (flag) {

            estudiantes.add(E);
            actualizarTabla(estudiantes);
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void EditarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarEstudianteActionPerformed

        Editar_estudiante EE = new Editar_estudiante(estudiantes.elementAt(TablaEst.getSelectedRow()));
        EE.setVisible(true);

    }//GEN-LAST:event_EditarEstudianteActionPerformed

    private void EliminarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEstudianteActionPerformed

        Estudiante E = estudiantes.elementAt(TablaEst.getSelectedRow());
        estudiantes.remove(E);
        
        G.eliminar_brigada_a_estudiante(E.getCI());

        actualizarTabla(estudiantes);

    }//GEN-LAST:event_EliminarEstudianteActionPerformed

    private void actualizarTabla(Vector<Estudiante> V) {
        DefaultTableModel df = new DefaultTableModel();
        TablaEst = new JTable(df);
        jScrollPane1.setViewportView(TablaEst);
        df.addColumn("Nombre del estudiante");
        df.addColumn("Carnet de Identidad");

        Object[] ob = new Object[2];
        for (int i = 0; i < V.size(); i++) {
            ob[0] = (String) V.elementAt(i).getNombre_estudiante();
            ob[1] = (String) V.elementAt(i).getCI();

            df.addRow(ob);
        }

        TablaEst.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila = TablaEst.rowAtPoint(e.getPoint());
                int columna = 0;

                if (fila > -1) {

                    String estudiante = (String) TablaEst.getValueAt(fila, columna);

                    MenuEstudiantes.setLocation(e.getPoint());
                    MenuEstudiantes.setVisible(true);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Agregar_estudiante;
    private javax.swing.JLabel Annos;
    private javax.swing.JComboBox<String> AnnosCombo;
    private javax.swing.JLabel CI;
    private javax.swing.JTextField CIT;
    private javax.swing.JLabel Carrera_seleccionada;
    private javax.swing.JMenuItem EditarEstudiante;
    private javax.swing.JMenuItem EliminarEstudiante;
    private javax.swing.JButton Finalizar;
    private javax.swing.JPopupMenu MenuEstudiantes;
    private javax.swing.JButton Seleccionar_carrera;
    private javax.swing.JTable TablaEst;
    private javax.swing.JDialog agregar_estudiante;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreT;
    // End of variables declaration//GEN-END:variables
}
