/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visuales;

import Base_de_Datos.Gestion;
import clases.Brigada;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import utiles.Secuencias_cadenas;
import static utiles.Secuencias_cadenas.sonNumeros;

/**
 *
 * @author joanmanuel
 */
public class Gestor_brigada extends javax.swing.JFrame {

    /**
     * Creates new form Gestor_brigada
     */
    private Gestion g;
    private Vector<String> carreras;
    private Vector<String> BrigadasCarrera;
    private Vector<String> BrigadasAnno;
    private Vector<String> BrigadasAnnoB;
    private boolean flag;
    private Vector<Brigada> Brigadas;

    public Gestor_brigada() {
        initComponents();
        g = new Gestion();
        carreras = g.obtener_carreras();
        BrigadasCarrera = new Vector<>();
        BrigadasAnno = new Vector<>();
        BrigadasAnnoB = new Vector<>();
        Brigadas = g.obtenerBrigadas();
        actualizarTablaBrigadas(Brigadas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableBrigadasExistentes = new javax.swing.JTable();
        editar = new javax.swing.JButton();
        LabelBeigadasExistentes = new javax.swing.JLabel();
        carreraBrigada = new javax.swing.JTextField();
        ButtonCancelar = new javax.swing.JButton();
        ComboBoxAnnos = new javax.swing.JComboBox<>();
        annoBrigada = new javax.swing.JLabel();
        anno = new javax.swing.JLabel();
        annoLabel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableBrigadasExistentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableBrigadasExistentes);

        editar.setText("Editar");
        editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarMouseClicked(evt);
            }
        });

        LabelBeigadasExistentes.setText("Brigadas Existentes");

        carreraBrigada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                carreraBrigadaKeyReleased(evt);
            }
        });

        ButtonCancelar.setText("Cancelar");

        ComboBoxAnnos.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                ComboBoxAnnosPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        annoBrigada.setText("Anno de la brigada");

        anno.setText("Anno");

        annoLabel.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonCancelar)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelBeigadasExistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(annoBrigada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ComboBoxAnnos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(anno)
                        .addGap(24, 24, 24)
                        .addComponent(annoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carreraBrigada, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelBeigadasExistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carreraBrigada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxAnnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(annoBrigada, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(anno)
                            .addComponent(annoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editar)
                    .addComponent(ButtonCancelar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carreraBrigadaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carreraBrigadaKeyReleased
        if (sonNumeros(evt.getKeyChar())) {
            Character caracterEtrada = evt.getKeyChar();
            String reeplazo = carreraBrigada.getText().replaceAll(caracterEtrada.toString(), "");
            carreraBrigada.setText(reeplazo);
        }
        Similares.removeAllElements();
        String temp = carreraBrigada.getText();
        if (temp.length() >= 3) {

            for (int i = 0; i < carreras.size(); i++) {
                if (Secuencias_cadenas.mayor_subcadena(temp, carreras.elementAt(i))) {
                    Similares.add(carreras.elementAt(i));
                }
            }
            actualizartablaCarreras(Similares);
        } else if (temp.length() < 3) {
            actualizartablaCarreras(carreras);
        }

    }//GEN-LAST:event_carreraBrigadaKeyReleased

    private void editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarMouseClicked
        if (!flag) {
            flag = true;
            if (!Similares.isEmpty()) {
                String carreraSeleccionada = Similares.elementAt(TableBrigadasExistentes.getSelectedRow());
                brigada = g.obtenerBrigadasDeUnaCarrera(carreraSeleccionada);
            } else {
                String carreraSeleccionada = carreras.elementAt(TableBrigadasExistentes.getSelectedRow());
                brigada = g.obtenerBrigadasDeUnaCarrera(carreraSeleccionada);
            }
        
            for (int i = 0; i < brigada.size(); i++) {
                ComboBoxAnnos.addItem((i + 1) + "");
            }
            ComboBoxAnnos.setSelectedIndex(0);
            ComboBoxAnnos.setVisible(true);
            LabelBeigadasExistentes.setText("Alumnos de la brigada");
            actualizarTablaBrigadas(brigada.elementAt(ComboBoxAnnos.getSelectedIndex()));
        }
        else if (flag){
            //retornar la brigada seleccionada para hacer los cambios que se vayan a hacer 
            Brigada b = brigada.elementAt(ComboBoxAnnos.getSelectedIndex());
            
        }
    }//GEN-LAST:event_editarMouseClicked

    private void ComboBoxAnnosPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboBoxAnnosPopupMenuWillBecomeInvisible
        actualizarTablaBrigadas(brigada.elementAt(ComboBoxAnnos.getSelectedIndex()));
    }//GEN-LAST:event_ComboBoxAnnosPopupMenuWillBecomeInvisible

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JComboBox<String> ComboBoxAnnos;
    private javax.swing.JLabel LabelBeigadasExistentes;
    private javax.swing.JTable TableBrigadasExistentes;
    private javax.swing.JLabel anno;
    private javax.swing.JLabel annoBrigada;
    private javax.swing.JTextField annoLabel;
    private javax.swing.JTextField carreraBrigada;
    private javax.swing.JButton editar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables


    private void actualizarTablaBrigadas(Vector<Brigada> V) {
        DefaultTableModel df = new DefaultTableModel();
        TableBrigadasExistentes = new JTable(df);
        jScrollPane1.setViewportView(TableBrigadasExistentes);
        df.addColumn("Nombre del Estudiante");
        df.addColumn("Carnet de Identidad");

        Object[] ob = new Object[2];
        for (int i = 0; i < b.getEstudiantes().size(); i++) {
            ob[0] = b.getEstudiantes().elementAt(i).getNombre_estudiante();
            ob[1] = b.getEstudiantes().elementAt(i).getCI();
            df.addRow(ob);
        }

    }
}
