/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visuales;

import Base_de_Datos.Gestion;
import clases.Carrera;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import utiles.Secuencias_cadenas;
import static utiles.Secuencias_cadenas.sonNumeros;
import utiles.dialogs.ConfirmDialog;

/**
 *
 * @author joanmanuel
 */
public class Gestor_carreras extends javax.swing.JFrame {

    
    private Vector<String> carreras;
    private Gestion G = new Gestion();
    private boolean Main;
    
    public Gestor_carreras(boolean Main) {
        initComponents();
        carreras = G.obtener_carreras();
        actualizarTabla(carreras);
        this.Main = Main;
        
        this.setLocationRelativeTo(null);
        this.setTitle("Gestor de carreras");
        
        
    }
    
    public void devolverValor(Object O){
    
        if(O instanceof Boolean){
            Boolean nO = (Boolean)O;
            
            if(nO==false){
                
            }
        }
    
    }
    
    
    private void actualizarTabla(Vector<String> V){
        
        DefaultTableModel df= new DefaultTableModel(){
        @Override
             public boolean isCellEditable(int row, int column) {
                return false;         
             };
        };
            Tabla_carreras= new JTable(df);
            jScrollPane1.setViewportView(Tabla_carreras);
            df.addColumn("Nombre de la carrera");
            
            Object[] ob = new Object[1];
            for (int i = 0; i < V.size(); i++) {
            ob[0] = V.elementAt(i);
            
            df.addRow(ob);
        }
            
             Tabla_carreras.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
            int fila = Tabla_carreras.rowAtPoint(e.getPoint());
            int columna = Tabla_carreras.columnAtPoint(e.getPoint());
            
            if(fila > -1){
                
                String carrera = (String)Tabla_carreras.getValueAt(fila, columna);
               
                if(Habilitar.isSelected()){
                    
                    int b = JOptionPane.showConfirmDialog(null, "¿Desea editar esta carrera?");
                    
                    if(b == 0){
                        
                    Carrera Carr = G.obtener_carrera(carrera);
                    Editor_carrera CC = new Editor_carrera(Carr, Main);                    
                    CC.setVisible(true);
                    dispose();
                    
                    }
                }
                
                if(!Habilitar.isSelected() && !Main){
                    int b = JOptionPane.showConfirmDialog(null, "¿Desea seleccionar esta carrera para la brigada?");
                    
                    
                    if(b == 0){
                    Editor_brigada CB = new Editor_brigada(carrera);
                    CB.setVisible(true);
                    dispose();
                    }
                }
               
            }
        }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre_carrera = new javax.swing.JLabel();
        Texto_carrera = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_carreras = new javax.swing.JTable();
        Crear_carrera = new javax.swing.JButton();
        Habilitar = new javax.swing.JRadioButton();
        Finalizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        gestorBrigadas = new javax.swing.JMenu();
        gestorCarreras = new javax.swing.JMenuItem();
        brigadasExistentes = new javax.swing.JMenuItem();
        gestorEventos = new javax.swing.JMenuItem();
        regresarMain = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Nombre_carrera.setText("Nombre de la carrera:");

        Texto_carrera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Texto_carreraKeyReleased(evt);
            }
        });

        Tabla_carreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla_carreras);

        Crear_carrera.setText("Crear nueva carrera");
        Crear_carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_carreraActionPerformed(evt);
            }
        });

        Habilitar.setText("Habilitar edición");

        Finalizar.setText("Atrás");
        Finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarActionPerformed(evt);
            }
        });

        gestorBrigadas.setText("Gestores");

        gestorCarreras.setText("Gestor de Carreras");
        gestorCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestorCarrerasActionPerformed(evt);
            }
        });
        gestorBrigadas.add(gestorCarreras);

        brigadasExistentes.setText("Gestor de Brigadas");
        brigadasExistentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                brigadasExistentesMouseReleased(evt);
            }
        });
        gestorBrigadas.add(brigadasExistentes);

        gestorEventos.setText("Gestor de Eventos");
        gestorEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestorEventosActionPerformed(evt);
            }
        });
        gestorBrigadas.add(gestorEventos);

        jMenuBar1.add(gestorBrigadas);

        regresarMain.setText("Regresar a la Ventana Principal");
        regresarMain.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                regresarMainMenuSelected(evt);
            }
        });
        regresarMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarMainActionPerformed(evt);
            }
        });
        jMenuBar1.add(regresarMain);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Nombre_carrera)
                .addGap(12, 12, 12)
                .addComponent(Texto_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Crear_carrera)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(Habilitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Finalizar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre_carrera)
                            .addComponent(Texto_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Crear_carrera))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Habilitar)
                    .addComponent(Finalizar))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Crear_carreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_carreraActionPerformed
        
         if(Texto_carrera.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No hay ningún nombre de carrera escrito en el campo de texto a la derecha de la etiqueta \" Nombre de la carrera\". Escriba uno para proceder");
        return;
        }
        
        String temp = Texto_carrera.getText();
        Vector<String> Similares = new Vector<>();
             for(int i = 0; i < carreras.size(); i++){
                 if(Secuencias_cadenas.LongestCommonSubsequence(temp, carreras.elementAt(i))>=75.00){
                     Similares.add(carreras.elementAt(i));
                 }
             }
             
             if(!Similares.isEmpty()){
             String[] S = new String[Similares.size()];
             Similares.copyInto(S);
             
                    String  x =(String) JOptionPane.showInputDialog(null, "Existen carreras con nombres similares al de la carrera que ha escrito. Seleccione uno de ellos o pulse en cancelar si no se ha equivocado.", "Sugerencia",JOptionPane.QUESTION_MESSAGE,null , S, S[0]);
            
                    if(x == null){  
                    Editor_carrera CC = new Editor_carrera(temp, Main);
                    CC.setVisible(true);
                    this.dispose();
                    }
                    
                    Vector<String> V = new Vector<String>();
                    V.add(x);
                    
                   actualizarTabla(V);
                    
             }
             else{
                 int opcion =JOptionPane.showConfirmDialog(null, "Comenzará el proceso de edición de la carrera \""+temp+"\". ¿Desea proceder?", "Mensaje de ayuda", JOptionPane.INFORMATION_MESSAGE);
                 if(opcion==0){
                  Editor_carrera CC = new Editor_carrera(temp, Main);
                    CC.setVisible(true);
                    this.dispose();
                 }
             }
    }//GEN-LAST:event_Crear_carreraActionPerformed

    private void Texto_carreraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Texto_carreraKeyReleased
        
          if(sonNumeros(evt.getKeyChar())){
            Character caracterEtrada = evt.getKeyChar();
            String reeplazo = Texto_carrera.getText().replaceAll(caracterEtrada.toString(),"");
            Texto_carrera.setText(reeplazo);
        }
         
          String temp = Texto_carrera.getText();
         if(temp.length()>=3){
             Vector<String> Similares = new Vector<>();
             for(int i = 0; i < carreras.size(); i++){
                 if(Secuencias_cadenas.mayor_subcadena(temp, carreras.elementAt(i))){
                     Similares.add(carreras.elementAt(i));
                 }
             }
             actualizarTabla(Similares);
         }
         else if(temp.length()<3){
             actualizarTabla(carreras);
         }
        
    }//GEN-LAST:event_Texto_carreraKeyReleased

    private void FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarActionPerformed
        Main m = new Main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FinalizarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
 
    }//GEN-LAST:event_formWindowClosed

    private void gestorCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestorCarrerasActionPerformed
        Gestor_carreras GC = new Gestor_carreras(true);
        GC.setVisible(true);
        dispose();
    }//GEN-LAST:event_gestorCarrerasActionPerformed

    private void brigadasExistentesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brigadasExistentesMouseReleased
        Gestor_brigada gestorBrigada = new Gestor_brigada(1);
        gestorBrigada.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_brigadasExistentesMouseReleased

    private void gestorEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestorEventosActionPerformed

        Gestor_eventos GE = new Gestor_eventos();
        GE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestorEventosActionPerformed

    private void regresarMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarMainActionPerformed
        
        Main M = new Main();
        M.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_regresarMainActionPerformed

    private void regresarMainMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_regresarMainMenuSelected
        
          Main M = new Main();
        M.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_regresarMainMenuSelected


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Crear_carrera;
    private javax.swing.JButton Finalizar;
    private javax.swing.JRadioButton Habilitar;
    private javax.swing.JLabel Nombre_carrera;
    private javax.swing.JTable Tabla_carreras;
    private javax.swing.JTextField Texto_carrera;
    private javax.swing.JMenuItem brigadasExistentes;
    private javax.swing.JMenu gestorBrigadas;
    private javax.swing.JMenuItem gestorCarreras;
    private javax.swing.JMenuItem gestorEventos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu regresarMain;
    // End of variables declaration//GEN-END:variables
}
